### ISSUE TITLE
can't start tracking_gui.py

### ISSUE THREAD

**Issue by ghost** [SainsburyWellcomeCentre/Pyper#45]
Can't start "tracking_gui.py". I have installed all the dependencies including python-opencv 3.2.0.

Traceback (most recent call last):
  File "tracking_gui.py", line 22, in <module>
    from gui_interfaces import ParamsIface, ViewerIface, TrackerIface, RecorderIface, CalibrationIface
  File "/home/philosophus/pyperMotionTracking/src/gui_interfaces.py", line 15, in <module>
    import cv2
ImportError: No module named cv2

**Comment by grandjeanlab** [comment]
same issue here. I think this is because the software requires opencv version 2.4.9, which is no longer available via pip install or aptitude (debian). 

On pip lowest version a 3.X
Any plan to update the software to modern opencv?

**Comment by crousseau** [comment]
The dev version (see dev branch) works with opencv3. It installs on all platforms using the compiled opencv/ffmpeg from conda (conda-forge channel). I'm pushing to get some spare time to finalise the release of v2 of pyper (the current in-dev) to the master branch in the near future.

**Comment by grandjeanlab** [comment]
Thank you :-)

**Comment by crousseau** [comment]
The newly pushed V2.0 should work with conda and fix all install/start problems
